language: java

services:
  - docker

deploy:
  provider: script
  script: bash push.sh
  on:
    branch: master

env:
  matrix:
  - USE_NETWORK=true
  - USE_NETWORK=false
 - secure: JfOTMD+6AfBe8WzpSNB654foocFxuhGLXygZhBuABCPSsaEjKQAaIW6dxFpfQ+pXN9avJTTsCpPmWjmYTCqx6U8LRwS1vlVoFCxqG0xzOHzQKqj+CS7ssUWmpNEFhPPb3uNUEQxUS1F9X4Oi80TrhnUFUrC1Pr4IGq96lgXay1zS62+DLgYM8LkAV2gprsVYpLt4vfK4dn0Z66gIo/wkXGeKB/meLyHO8dsO1sfAa2Oq7kIxucDJBuE1pnegO5LjCC4yGd7d4YT82la+Xy0PnFIeQIiX52qbBMn0xF3gJjn45qstO2Bz2g8AieObXbrSzQ/X55pTQ51Ycsr+OIDRFrj3nCAOooODwRGhSy2yBQeprI+LYbjAPzJY1SDS3hnpCXxh6YV1LWNPkL0w89AMHp+Gbk8iGsPsup+WHKd1I3nIDDJXnJWB1nnMy1ZpUtLnb6oH/VuFs4DofUR5BZJfXBUqIjVC39tWC/dgS2znb4bErRpRcTT41J0FnG8AQXeavKn68Fl9bYAjMURlI5kLUw7Wg587R/imXegLuj7g9hZyGUeRboJkvwKz30RTzA0AvNtBe75ewKD3TGXvxRILIgdJ93ua64kSFtfhGKvK3OpXi+toWdGKox4LQX35eIi7i2VuZ7vDBGIxr/1Yh1lxaWplhXyXZEbH9KKbwgJy84A=

